
apiVersion: apps/v1
kind: Deployment
metadata:
  name: david_front-end-site
spec:
  replicas: 2
  selector:
    matchLabels:
      app: david_front-end-site
  template:
    metadata:
      labels:
        app: david_front-end-site
    spec:
      containers:
      - name: david-front-end-site
        imagePullPolicy: Always
        image: davidbolarinwa/david_front-end_site:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: qr-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: qr-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
