apiVersion: apps/v1
kind: Deployment
metadata:
  name: david-front-end-site  
  labels:
    app: david-front-end-site 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: david-front-end-site 
  template:
    metadata:
      labels:
        app: david-front-end-site  
    spec:
      - name: david-front-end-site
        image: davidbolarinwa/david_front-end_site:1.0.0
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: david-front-end-site 
spec:
  type: LoadBalancer
  selector:
    app: david-front-end-site  
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
