name: Build Aws Resources
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'infrastucture/*'
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: deploy resources
        run: |
          cd infrastucture
          terraform init
          terraform apply -auto-approve
      - name: destroy resources
        run: |
          cd infrastucture
          terraform destroy -auto-approve